# Generated by Django 4.2.8 on 2023-12-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
            ],
            options={
                'verbose_name': 'Property Manager',
                'verbose_name_plural': 'Property Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
