target-version = "py311"


[tool.ruff.lint]
# Enable Pyflakes `E` and `F` codes by default.
select = [
    # pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["E501", "E741", "F401", "S101", "S106", "S308"]

[tool.djlint]
profile="django"
ignore = "H031,H006,H030,H021"
