# Generated by Django 4.2.8 on 2023-12-21 14:10

from django.db import migrations, models

import contracts.models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='second_mpan_mpr',
            field=models.IntegerField(blank=True, null=True, validators=[contracts.models.validate_no_decimal], verbose_name='MPAN/MPR'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='second_mpan_mpr',
            field=models.IntegerField(blank=True, null=True, validators=[contracts.models.validate_no_decimal], verbose_name='MPAN/MPR'),
        ),
    ]
